name: WordPress CI

on:
  push:
    branches:
      - main
      - "feature/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Install PHP_CodeSniffer
        run: composer global require "squizlabs/php_codesniffer=*"
      - name: Install WordPress Coding Standards
        run: |
          git clone -b master https://github.com/WordPress/WordPress-Coding-Standards.git wpcs
          phpcs --config-set installed_paths wpcs
          phpcs -i
      - name: Lint
        run: phpcs --standard=WordPress .
